---
title: "3 Point Attempt and Offensive Rebound Percentage Correlation Analysis"
author: "Brett Lang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(reticulate)
```

```{python}
from nba_api.stats.endpoints import leaguedashteamstats
import pandas as pd
import time

def get_season_data(season_year):
    
    # Regular season advanced stats (for 3PAr and OREB%)
    reg = leaguedashteamstats.LeagueDashTeamStats(
        season=season_year,
        season_type_all_star="Regular Season",
        measure_type_detailed_defense="Advanced"
    )
    df_reg = reg.get_data_frames()[0]
    df_reg = df_reg[["TEAM_ID", "TEAM_NAME", "OREB_PCT", "TM_TOV_PCT"]]
    
    time.sleep(1)
    
    # Regular season base stats (for 3PAr = FG3A / FGA)
    reg_base = leaguedashteamstats.LeagueDashTeamStats(
        season=season_year,
        season_type_all_star="Regular Season"
    )
    df_base = reg_base.get_data_frames()[0]
    df_base["THREE_PT_ATTEMPT_RATE"] = df_base["FG3A"] / df_base["FGA"]
    df_base = df_base[["TEAM_ID", "THREE_PT_ATTEMPT_RATE"]]
    
    time.sleep(1)
    
    # Playoff win percentage
    po = leaguedashteamstats.LeagueDashTeamStats(
        season=season_year,
        season_type_all_star="Playoffs"
    )
    df_po = po.get_data_frames()[0]
    df_po = df_po[["TEAM_ID", "W_PCT"]].rename(columns={"W_PCT": "W_PCT_PO"})
    
    # Merge all three
    df = pd.merge(df_reg, df_base, on="TEAM_ID")
    df = pd.merge(df, df_po, on="TEAM_ID")
    
    return df
```

```{python}
years = ["2015-16","2016-17","2017-18","2018-19","2019-20",
  "2020-21","2021-22","2022-23","2023-24","2024-25"]

all_season_data = []

for year in years:
    season_df = get_season_data(year)
    season_df["season"] = year
    all_season_data.append(season_df)
    time.sleep(2)

combined_df = pd.concat(all_season_data, ignore_index = True)
```

```{r}
library(dplyr)
combined_df <- py$combined_df
combined_df
```

```{r}
cors <- combined_df %>%
  group_by(season) %>%
  summarize(
    cor_3par = cor(THREE_PT_ATTEMPT_RATE, W_PCT_PO),
    cor_oreb = cor(OREB_PCT, W_PCT_PO)
  )

cors
```

```{r}
mean(cors$cor_3par)
mean(cors$cor_oreb)
```